### ISSUE TITLE
ChromiumWebBrowser won't be disposed unless calling Dispose explicitly.

### ISSUE THREAD

**Issue by kkwpsv** [cefsharp/CefSharp.Wpf.HwndHost#13]
HwndHost will call `Dispose` in `~HwndHost()`. So it could be disposed implicitly.
But in `ChromiumWebBrowser`, the instance has be added to a static `HashSet` by `AddDisposable`, so it'll never be finalized.

Maybe we should add CleanupElement for it?

**Comment by campersau** [comment]
And maybe a finalizer?

```c#
~ChromiumWebBrowser()
{
    Dispose(false);
}
```

**Comment by kkwpsv** [comment]
> And maybe a finalizer?
> 
> ```cs
> ~ChromiumWebBrowser()
> {
>     Dispose(false);
> }
> ```

There's already a finalizer. But the class is referenced by the static `HashSet`. It won't be gc , and won't be finalized.

**Comment by amaitland** [comment]
You can add a class that implements Idisposable, holds a weak reference to the ChromiumWebBrowser instance, pass that to Cef.AddDisposable.

**Comment by kkwpsv** [comment]
> You can add a class that implements Idisposable, holds a weak reference to the ChromiumWebBrowser instance, pass that to Cef.AddDisposable.

I didn't understand why pass that to `Cef.AddDisposable` again? What you want to say is `Cef.RemoveDisposable`?

**Comment by amaitland** [comment]
I'm suggesting instead of passing a direct reference to Cef.AddDisposable passing what is effectively a weak reference. The remove call would also Need to be updated. 

https://github.com/cefsharp/CefSharp.Wpf.HwndHost/blob/master/CefSharp.Wpf.HwndHost/ChromiumWebBrowser.cs#L536

**Comment by amaitland** [comment]
> HwndHost will call Dispose in ~HwndHost(). So it could be disposed implicitly.
But in ChromiumWebBrowser, the instance has be added to a static HashSet by AddDisposable, so it'll never be finalized.

This is the problem you've stated, and that's the problem I'm suggesting a solution for.

**Comment by kkwpsv** [comment]
I'd like to introduce `CleanupElement` like CefSharp.Wpf. Is it acceptable to merge? If so, I'll make a pull request later.

**Comment by amaitland** [comment]
> I'd like to introduce `CleanupElement` like CefSharp.Wpf. Is it acceptable to merge? If so, I'll make a pull request later.

Is it actually required? Have you tried the default `HwndHost` behaviour?

**Comment by amaitland** [comment]
For reference the shutdown code now matches the `WPF` implementation and will close all `ChromiumWebBrowser` instances when the `Dispatcher` is shutdown. See https://github.com/cefsharp/CefSharp.Wpf.HwndHost/commit/c5c6d486a1748162cf63f5920f1aedad34ea5033

**Comment by amaitland** [comment]
> Is it actually required? Have you tried the default `HwndHost` behaviour?

To be clear, comment out the `Cef.AddDisposable` call and see how the `HwndHost` finalizer behaves, the control will still be `Disposed` when the `Dispatcher.ShutdownFinished`

https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Interop/HwndHost.cs,1423

**Comment by kkwpsv** [comment]
> > Is it actually required? Have you tried the default `HwndHost` behaviour?
> 
> To be clear, comment out the `Cef.AddDisposable` call and see how the `HwndHost` finalizer behaves, the control will still be `Disposed` when the `Dispatcher.ShutdownFinished`
> 
> https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Interop/HwndHost.cs,1423

Hwndhost is not only be disposed when `Dispatcher.ShutdownFinished`. It's also be disposed when gc in it's finalizer. You can see this behavior from the following sample.

I create a new Window, and put a HwndHost in it. Close the window, wait and call GC. You can see that the finalizer of Hwndhost is called while main thread is waiting for finalizer.

![image](https://user-images.githubusercontent.com/11524048/131969314-dd6882c5-424c-4141-bf0b-9e27286b6474.png)
![image](https://user-images.githubusercontent.com/11524048/131969636-79762423-e815-463b-8ae2-28971427f244.png)
![image](https://user-images.githubusercontent.com/11524048/131969719-c520a84f-6211-43c1-9f7e-77bace934ef6.png)

**Comment by amaitland** [comment]
> Hwndhost is not only be disposed when Dispatcher.ShutdownFinished. It's also be disposed when gc in it's finalizer

I'm aware of this. 

I was simply making you aware of the change. I'm not suggesting this is a fix.

> I create a new Window, and put a HwndHost in it. Close the window, wait and call GC. You can see that the finalizer of Hwndhost is called while main thread is waiting for finalizer. And the Dispatcher is still alive. It hasn't shutdown.

Please no images of code.

**Comment by kkwpsv** [comment]
I misunderstood that you missed the finalizer could be called by gc. So I just use images to show the callstack and calling sequence.

I think `CleanupElement` shuold be useful. In projects, it's easy to write some code in handler or other that reference to `ChromiumWebBrowser`, which cause it not be disposed by gc, and cause serious resource leak. With `CleanupElement`, most of unmanaged resource could be disposed. And disposing when `Dispatcher.ShutdownFinished` may has less impact, because the event usually be raised when the program is about to exit. Even without disposed, resource will be released by os.

Just removing the reference by `Cef.AddDisposable` should be useful for this issues. But in larger project, it's not as robust as `CleanupElement`. I prefer to use `CleanupElement`.

**Comment by amaitland** [comment]
Submit a PR for cleanup element. Making sure all methods are documented and changing of parent windows is handled correctly.

**Comment by kkwpsv** [comment]
OK, I'll submit it later.

**Comment by amaitland** [comment]
Version `93.1.140` includes `ChromiumWebBrowser.CleanupElement` though you have to assign it manually at the moment.

**Comment by amaitland** [comment]
`CleanupElement` will now be set when the browser is added/moved to a `Window`. Commit https://github.com/cefsharp/CefSharp.Wpf.HwndHost/commit/54a6b507529e34ce99af01dfb0e05e4fa2e098d8
