### ISSUE TITLE
Host app can't get drag/drop events in browser area.

### ISSUE THREAD

**Issue by yowu** [cefsharp/CefSharp.Wpf.HwndHost#15]
I used to use CefSharp WPF control and can handle some drag/drop events from my host app, e.g. drop a specified type file my app supported in the browser area and I could handle it in my host app drag/drop handler to open it in another view. 
But, in the test of this new control, it doesn't work anymore.  It looks like the browser can detect the drag/drop events, but the host app never be notified.

**Comment by amaitland** [comment]
That behaviour is as expected. Chromium handles all events same as WinForms. 

You can access drag information via http://cefsharp.github.io/api/95.7.x/html/M_CefSharp_IDragHandler_OnDragEnter.htm
