### ISSUE TITLE
Incorrect browser render on resize if WindowChrome is set

### ISSUE THREAD

**Issue by Decious** [cefsharp/CefSharp.Wpf.HwndHost#16]
Hello! I seem to have encountered a bug on CefSharp.Wpf.HwndHost 97.1.61. 
If WindowChrome on the window is set and CefBrowser has a fixed size, browser will be rendered outside of the client area when resizing the window.
![Cef](https://user-images.githubusercontent.com/47895095/151836866-8b8fa384-3763-4570-a0a0-d1473316e22b.gif)
This behaviour can only be seen if resizing the window does not change browser's size or move it anywhere.

**Comment by amaitland** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.interop.hwndhost?view=windowsdesktop-6.0

Are you sure this isn't a limitation of HwndHost? Standard airspace issues apply. If you are not familiar then read https://dwayneneed.github.io/wpf/2013/02/26/mitigating-airspace-issues-in-wpf-applications.html

See also https://social.msdn.microsoft.com/Forums/vstudio/en-US/5225f2a6-a648-40c4-9a22-20ff1b789706/sizing-problem-for-win32-control-hosted-in-wpf?forum=wpf

**Comment by Decious** [comment]
Perhaps I might've posted an issue too early. I managed to fix this resizing issue by setting Left/Right sides as NonClientFrameEdges in WindowChrome and extending window clientarea via winApi calls to hide the default frame border on that side. Although I'm curious why cefsharp is the only control that has this issue, I've tried a couple of other controls with WindowsFormsHost and couldn't reproduce this problem

**Comment by amaitland** [comment]
> Although I'm curious why cefsharp is the only control that has this issue

Have you confirmed this is CefSharp specific? Have you tested another CEF based browser? 

> I've tried a couple of other controls with WindowsFormsHost and couldn't reproduce this problem

Chromium does most of it's rendering in a different process, you can try using the https://peter.sh/experiments/chromium-command-line-switches/#in-process-gpu command line argument and see if you get a different behaviour. 

Sounds like you have a viable workaround. At this point in time I'm not planning on debugging this myself, if you plan on investing further then I'll leave this open.

**Comment by amaitland** [comment]
Closing due to lack of feedback.
