### ISSUE TITLE
cannot be null (Parameter `browserSettings`) at CefSharp.Core.ManagedCefBrowserAdapter.CreateBrowser(CefSharp.IWindowInfo, CefSharp.IBrowserSettings, CefSharp.IRequestContext, System.String)

### ISSUE THREAD

**Issue by SLT-World** [cefsharp/CefSharp.Wpf.HwndHost#18]
cannot be null (Parameter `browserSettings`) at CefSharp.Core.ManagedCefBrowserAdapter.CreateBrowser(CefSharp.IWindowInfo, CefSharp.IBrowserSettings, CefSharp.IRequestContext, System.String)

What version of the product are you using?
- Version: 104.4.240

What architecture x86 or x64?
- App Architecture: AnyCPU
- System Architecture: 64-bit

On what operating system?
- OS: Win10, 64-bit, x64 based processor

Are you using WinForms, WPF or OffScreen?
- Using CefSharp.Wpf.HwndHost in .NET Core 6.0

What steps will reproduce the problem?
- In SLBr (With CefSharp.Wpf.HwndHost. I removed CefSharp.Wpf.HwndHost in SLBr's source code though), there must be 10 not initalized tabs, go to the first tab, open settings tab, select to settings tab, select and close the two tabs on the right, click back to settings tab, then click on the first tab.

What is the expected output? What do you see instead?
- My expected output is that it shows the site view instead of the null browsersettings error. This error does not happen in CefSharp.Wpf, so I believe this is a bug in CefSharp.Wpf.Hwndhost. It seems to also crash the browser without visual studio catching the error. This error only appears if a tab with chromiumwebbrowser is selected, there are multiple other ways to trigger this error with the usage of tabs but I can't track most of them

Please provide any additional information below.
- A stack trace if available, any Exception information.
![Screenshot (2439)](https://user-images.githubusercontent.com/76160587/188403694-26428579-2643-4e22-b66a-89d58efbbfc5.png)
- Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
The problem does not exist on the normal CefSharp.Wpf without Hwndhost

Does this problem also occur in the CEF Sample Application from http://opensource.spotify.com/cefbuilds/index.html?
- No I can't reproduce this problem on a tabless environment. And it only occurs in CefSharp.Wpf.Hwndhost

**Comment by amaitland** [comment]
> * In SLBr

What is `SLBr` exactly?

> * there must be 10 not initalized tabs, go to the first tab, open settings tab, select to settings tab, select and close the two tabs on the right, click back to settings tab, then click on the first tab.

This seems overly complex, can you provide a simpler example?

Debugging wise I'd suggest adding a break point to https://github.com/cefsharp/CefSharp.Wpf.HwndHost/blob/master/CefSharp.Wpf.HwndHost/ChromiumWebBrowser.cs#L739

**Comment by SLT-World** [comment]
**What is SLBr exactly?**
- It's just a tabbed browser, don't mind that.

**This seems overly complex, can you provide a simpler example?**
- I made a small tabbed environment that only needs 4 tabs to reproduce, I attached a video here on how to reproduce the exception

Tabbed project
https://github.com/SLT-World/TabbedHwndHostCefSharp

**Debugging wise I'd suggest adding a breakpoint to**
- I'm not sure how to add a breakpoint to a code that's in a package, I'm not quite the expert at debugging errors, sorry.

https://user-images.githubusercontent.com/76160587/188570680-b8d90a3d-05fd-42f5-a579-d73cd9bf4be7.mp4

**Comment by amaitland** [comment]
> * I made a small tabbed environment that only needs 4 tabs to reproduce, I attached a video here on how to reproduce the exception

Great, thanks 👍 

I believe the problem stems from the `TabControl` recreating it's children see https://stackoverflow.com/questions/9794151/stop-tabcontrol-from-recreating-its-children for background.

Using a modified `TabControl` is generally the approach I'd go for when using a browser see http://stackoverflow.com/a/9802346

Will have to see if we can reparent the `CefBrowser` instance to avoid the crash.

**Comment by amaitland** [comment]
> I believe the problem stems from the `TabControl` recreating it's children see https://stackoverflow.com/questions/9794151/stop-tabcontrol-from-recreating-its-children for background.

Actually this isn't quite correct, the `HwndHost` kindly reparents the `HWND` to a message only window, which is why switching tabs works on, when closing a tab `ChromiumWebBrowser.Dispose` triggers the internal `CefBrowser` to close, which by default `CEF` will send a `WM_CLOSE` message by default which appears to be the problem, the tab change then tries to recreate the `HWND` via `BuildWindowCore`.

Added a `LifeSpanHandler` implementation which is set by default to stop sending the `WM_CLOSE` message for the main browser. Popups are still allowed to close.

Anyone implementing those own custom `LifeSpanHandler` will need to implement similar logic, see https://github.com/cefsharp/CefSharp.Wpf.HwndHost/commit/e9ec88a8b3c419c03f2edde0ffaa40ca62dd914d for what's happening internally now.
