### ISSUE TITLE
In CefSharp.Wpf.HwndHost.Example to the MainWindow form Example.AddPreviewKeyDown="Window_PreviewKeyDown" event to MainWindow form, I found that it can't be triggered by breakpoint, but if I don't initialize hwndhost:ChromiumWebBrowser, I found that it can be triggered by PreviewKeyDo event, please help me to guide it, thank you!

### ISSUE THREAD

**Issue by tianqi20230628** [cefsharp/CefSharp.Wpf.HwndHost#23]
CefSharp.Wpf.HwndHost.Example to the MainWindow form
Example.AddPreviewKeyDown="Window_PreviewKeyDown" event to MainWindow form, I found that it can't be triggered by breakpoint, but if I don't initialize hwndhost:ChromiumWebBrowser, I found that it can be triggered by PreviewKeyDo event, please help me to guide it, thank you!

**Comment by amaitland** [comment]
`Chromium` handles all keyboard/mouse events that are sent to the browser. If the browser has focus then that's entirely expected.


You can implement `IKeyboardHandler` and assign and instance to the [KeyboardHandler](https://cefsharp.github.io/api/118.6.x/html/P_CefSharp_IWebBrowser_KeyboardHandler.htm) property to get the low level messages from chromium.

https://github.com/cefsharp/CefSharp/wiki/General-Usage#handlers

**Comment by tianqi20230628** [comment]
> `Chromium`处理发送到浏览器的所有键盘/鼠标事件。如果浏览器具有焦点，那么这是完全可以预料的。
> 
> 您可以实现`IKeyboardHandler`并将实例分配给[KeyboardHandler](https://cefsharp.github.io/api/118.6.x/html/P_CefSharp_IWebBrowser_KeyboardHandler.htm)属性，以从 chromium 获取低级消息。
> 
> https://github.com/cefsharp/CefSharp/wiki/General-Usage#handlers


Thank you
