### ISSUE TITLE
RequestContext type on HwndHost ChromiumWebBrowser check is too strict

### ISSUE THREAD

**Issue by mitchcapper** [cefsharp/CefSharp.Wpf.HwndHost#30]
it requires it to be the exact RequestContext type, this prohibits using things like the Fluent Builder.  Not sure if this difference with master is intentional or this was just never migrated over.

**Comment by amaitland** [comment]
> Not sure if this difference with master is intentional or this was just never migrated over.

Was just never migrated. Happy to see it changed. Thanks for the `PR`! Will give it a quick test shortly.
