### ISSUE TITLE
Browser rendered as Legacy Chrome Browser

### ISSUE THREAD

**Issue by lupusilviu** [cefsharp/CefSharp.Wpf.HwndHost#4]
Hello,

I am using this solution, to render a page, on Windows 10.
On a computer, works without a problem, I can access the browser with Automations, I can inspect buttons and everything.

When I put the entire code on another machine, the page is rendered, but I cannot use automations anymore, as it renders the control as a Legacy Chrome Browser. Any idea why this is hapenning? 

Thank you for any ideas.

**Comment by lupusilviu** [comment]
Also, on the PC that is rendered as Legacy Chrome, when I had AllowTransparency = true, it was all Black, but I could see that there was a page renderedm because the cursor changed depending on where it was hovering.

**Comment by lupusilviu** [comment]
Partially fixed the problem. Seems it was actually a Chrome issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=628922

More exactly:
Chrome doesn't enable accessibility unless it detects a screen reader or other advanced use of the accessibility APIs. To enable it manually, you can start Chrome with the --force-renderer-accessibility command-line flag, or visit chrome://accessibility to enable it for one session.

**Comment by amaitland** [comment]
> when I had AllowTransparency = true, it was all Black

Transparency is not supported. This is a limitation of the WPF framework. https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/technology-regions-overview details some of the fundamental limitations of hosting a win32 control in WPF. 

> Partially fixed the problem. Seems it was actually a Chrome issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=628922

Fundamentally chromium implements accessibility, the functionality should practically be the same as chromium at the same version. 

You can use http://cefsharp.github.io/api/83.4.x/html/M_CefSharp_IBrowserHost_SetAccessibilityState.htm to enable/disable at runtime. 

Personally I've never had a need to use the accessibility features, any further questions would be best asked on https://magpcss.org/ceforum/index.php
