### ISSUE TITLE
Browser loses focus after switching to other application and switching back

### ISSUE THREAD

**Issue by smallb2007** [cefsharp/CefSharp.Wpf.HwndHost#5]
I ran the example in https://github.com/cefsharp/CefSharp.Wpf.HwndHost/tree/master/CefSharp.Wpf.HwndHost.Example to load google.com. I typed in the input box. Then I switched to other windows by Alt + Tab and switched back to CefSharp.Wpf.HwndHost.Example. The keyboard no longer focused on the input box. I was not able to use tab key to get the focus back.

I tried to integrate CEF into my applications existing message loop by following ttps://github.com/cefsharp/CefSharp/wiki/General-Usage#multithreadedmessageloop. However the cef browser did not get back the focus.

**Comment by amaitland** [comment]
Focus should now correctly switch when using TAB. I've other focus related improvements have also been made.

- Tab into browser from adjacent WPF control
- Tab out of browser (previously just cycled between html elements within the browser).

We need to left WPF know when the HWND host has focus. I'll open a new issue for that.

**Comment by amaitland** [comment]
An updated build is now available https://www.nuget.org/packages/CefSharp.Wpf.HwndHost/85.3.121
