### ISSUE TITLE
Error XDG0062

### ISSUE THREAD

**Issue by R5GAMER** [cefsharp/CefSharp.Wpf.HwndHost#9]
i have this error when i write wpf:ChromiumBrowser x:Name"Web"

Severity	Code	Description	Project	File	Line	Suppression State
Error	XDG0062	Method not found: 'Boolean CefSharp.IBrowserSettings.get_FrameworkCreated()'.

**Comment by amaitland** [comment]
What version are you using?

> write wpf:ChromiumBrowser x:Name"Web"

Is that the actual `xaml` you are using? It looks invalid to me.

**Comment by R5GAMER** [comment]
Yes is in xaml, i used last version.

**Comment by amaitland** [comment]
Please provide the exact xaml you are using,  the xaml you provided is invalid. 

Your xaml should look like https://github.com/cefsharp/CefSharp.Wpf.HwndHost/blob/master/CefSharp.Wpf.HwndHost.Example/MainWindow.xaml#L45

You can download and build the project from source and see if you can reproduce the problem. 

There's insufficient detail currently.

**Comment by R5GAMER** [comment]
The example folder said error :

  | Name | Value | Type
-- | -- | -- | --
◢ | $exception | {"Méthode not found : 'Void CefSharp.ManagedCefBrowserAdapter..ctor(CefSharp.Internals.IWebBrowserInternal, Boolean)'."} | System.MissingMethodException

**Comment by amaitland** [comment]
Commit https://github.com/cefsharp/CefSharp.Wpf.HwndHost/commit/b76b3f8d6dc1fc18e86ba6f7f6151c2cc1fab49a built successfully. See
https://ci.appveyor.com/project/cefsharp/cefsharp-wpf-hwndhost/builds/36673695

Last time I tried building locally was successful. At this stage it looks like a problem with your development environment. 

I've not had any other reports of a problem.

**Comment by R5GAMER** [comment]
I try to git clone and not download and i test it

**Comment by R5GAMER** [comment]
There are not transparency ?

**Comment by amaitland** [comment]
Only the CefSharp.Wpf.ChromiumWebBrowser implementation supports transparency. It is not possible to implement it in the HwndHost implementation.
